trigger:
- main
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build_api
    displayName: Build API
    steps:
      - template: ./build-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/api'
- job: Build_frontend
    displayName: Build Frontend
    steps:
      - template: ./build-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/frontend'
          buildProject: true
- stage: Test
  displayName: Test stage
  jobs:  
  - job: Test_api
    displayName: Test API
    steps:
      - template: ./sonarcloud-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/api'
- job: Test_frontend
    displayName: Test Frontend
    steps:
      - template: sonarcloud-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/frontend'
- stage: Build_dockerimage
  displayName: Build and push image to ACR stage
  jobs:  
  - job: Build_api_dockerimage
    displayName: Build and push API image
    steps:
      - template: ./docker-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/api/dockerfile'
- job: Build_frontend_dockerimage
    displayName: Build and push frontend image
    steps:
      - template: ./docker-template.yml
        parameters:
          workingDirectory: '$(Build.Repository.LocalPath)/frontend/dockerfile'